services:
  backend:
    image: ${REGISTRY_IP}:5000/estudio-backend:latest
    platform: linux/arm/v8
    ports:
      - "${BACKEND_PORT}:8000"
    volumes:
      - uploads:/app/uploads
      - debug:/app/debug
    environment:
      - UPLOAD_DIR=/app/uploads
      - DEBUG_DIR=/app/debug
      - MAX_FILE_SIZE=104857600
      - CHUNK_SIZE=1048576
      - CORS_ORIGINS=http://${HOST_IP}:${FRONTEND_PORT}
    restart: unless-stopped

  frontend:
    image: ${REGISTRY_IP}:5000/estudio-frontend:latest
    platform: linux/arm/v8
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://${HOST_IP}:${BACKEND_PORT}
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
    restart: unless-stopped

volumes:
  uploads:
  debug:

